[build]
  command = "npm run build"
  publish = "/build"
  functions = "functions/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "script-src 'unsafe-inline' 'self'"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "interest-cohort=()"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST GET OPTIONS"
    Access-Control-Allow-Headers = "*"